### ISSUE TITLE
workIncipit

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/owl-schema#42]
We have two things related with incipit in the schema: a class `:WorkIncipit` and a data property `:workIncipit`, I believe one of them is erroneous, maybe the class?

**Comment by eroux** [comment]
Looking closer, there are two different things that would go in the `:workIncipit` data property:

```xml
<work:title type="incipit">...
```

 and

```xml
<work:description type="incipit">...
```

I think it's good if both if the two get migrated in the same way, but I thought I'd ask before...?

**Comment by xristy** [comment]
I do not see any uses of `<work:title type="incipit">...` in the current db. Since incipit is:

> the opening words of a text, manuscript, early printed book, or chanted liturgical text.

it would have made some sense for it to be treated as a title when none other was evident, but apparently has not been used.

Otherwise the idea of mapping the two together would be fine, but now not necessary.
